// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StataHelper.Model.Context;

namespace StataHelper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("StataHelper.Model.LabelCollections", b =>
                {
                    b.Property<short>("LabelCollectionsID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("LabelCollectionsID");

                    b.ToTable("LabelCollections");

                    b.HasData(
                        new
                        {
                            LabelCollectionsID = (short)1,
                            Description = "Short name of months of the year",
                            LabelName = "Short Months"
                        },
                        new
                        {
                            LabelCollectionsID = (short)2,
                            Description = "Full name of months of the year",
                            LabelName = "Full Months"
                        },
                        new
                        {
                            LabelCollectionsID = (short)3,
                            Description = "Short name of days of the week",
                            LabelName = "Short Weeks"
                        },
                        new
                        {
                            LabelCollectionsID = (short)4,
                            Description = "Full name of days of the week",
                            LabelName = "Full Weeks"
                        },
                        new
                        {
                            LabelCollectionsID = (short)5,
                            Description = "Short gender",
                            LabelName = "Short Gender"
                        },
                        new
                        {
                            LabelCollectionsID = (short)6,
                            Description = "Long gender",
                            LabelName = "Long Gender"
                        },
                        new
                        {
                            LabelCollectionsID = (short)7,
                            Description = "Short form of yes/no responses",
                            LabelName = "Short Yes/Nos"
                        },
                        new
                        {
                            LabelCollectionsID = (short)8,
                            Description = "Long form of yes/no responses",
                            LabelName = "Long Yes/No's"
                        },
                        new
                        {
                            LabelCollectionsID = (short)9,
                            Description = "True of false represented as T/F",
                            LabelName = "Short True/False"
                        },
                        new
                        {
                            LabelCollectionsID = (short)10,
                            Description = "True of false as is",
                            LabelName = "True/False"
                        });
                });

            modelBuilder.Entity("StataHelper.Model.Labels", b =>
                {
                    b.Property<int>("LabelsID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<byte>("Key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<short>("LabelCollectionsID");

                    b.HasKey("LabelsID");

                    b.HasIndex("LabelCollectionsID");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            LabelsID = 1,
                            Key = (byte)1,
                            Label = "Jan",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 2,
                            Key = (byte)2,
                            Label = "Feb",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 3,
                            Key = (byte)3,
                            Label = "Mar",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 4,
                            Key = (byte)4,
                            Label = "Apr",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 5,
                            Key = (byte)5,
                            Label = "May",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 6,
                            Key = (byte)6,
                            Label = "Jun",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 7,
                            Key = (byte)7,
                            Label = "Jul",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 8,
                            Key = (byte)8,
                            Label = "Aug",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 9,
                            Key = (byte)9,
                            Label = "Sep",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 10,
                            Key = (byte)10,
                            Label = "Oct",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 11,
                            Key = (byte)11,
                            Label = "Nov",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 12,
                            Key = (byte)12,
                            Label = "Dec",
                            LabelCollectionsID = (short)1
                        },
                        new
                        {
                            LabelsID = 13,
                            Key = (byte)1,
                            Label = "January",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 14,
                            Key = (byte)2,
                            Label = "February",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 15,
                            Key = (byte)3,
                            Label = "March",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 16,
                            Key = (byte)4,
                            Label = "April",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 17,
                            Key = (byte)5,
                            Label = "May",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 18,
                            Key = (byte)6,
                            Label = "June",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 19,
                            Key = (byte)7,
                            Label = "July",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 20,
                            Key = (byte)8,
                            Label = "August",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 21,
                            Key = (byte)9,
                            Label = "September",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 22,
                            Key = (byte)10,
                            Label = "October",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 23,
                            Key = (byte)11,
                            Label = "November",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 24,
                            Key = (byte)12,
                            Label = "December",
                            LabelCollectionsID = (short)2
                        },
                        new
                        {
                            LabelsID = 25,
                            Key = (byte)1,
                            Label = "Mon",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 26,
                            Key = (byte)2,
                            Label = "Tue",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 27,
                            Key = (byte)3,
                            Label = "Wed",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 28,
                            Key = (byte)4,
                            Label = "Thur",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 29,
                            Key = (byte)5,
                            Label = "Fri",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 30,
                            Key = (byte)6,
                            Label = "Sat",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 31,
                            Key = (byte)7,
                            Label = "Sun",
                            LabelCollectionsID = (short)3
                        },
                        new
                        {
                            LabelsID = 33,
                            Key = (byte)1,
                            Label = "Monday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 34,
                            Key = (byte)2,
                            Label = "Tuesday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 35,
                            Key = (byte)3,
                            Label = "Wednesday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 36,
                            Key = (byte)4,
                            Label = "Thursday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 37,
                            Key = (byte)5,
                            Label = "Friday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 38,
                            Key = (byte)6,
                            Label = "Saturday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 39,
                            Key = (byte)7,
                            Label = "Sunday",
                            LabelCollectionsID = (short)4
                        },
                        new
                        {
                            LabelsID = 40,
                            Key = (byte)0,
                            Label = "F",
                            LabelCollectionsID = (short)5
                        },
                        new
                        {
                            LabelsID = 41,
                            Key = (byte)1,
                            Label = "M",
                            LabelCollectionsID = (short)5
                        },
                        new
                        {
                            LabelsID = 42,
                            Key = (byte)0,
                            Label = "Female",
                            LabelCollectionsID = (short)6
                        },
                        new
                        {
                            LabelsID = 43,
                            Key = (byte)1,
                            Label = "Male",
                            LabelCollectionsID = (short)6
                        },
                        new
                        {
                            LabelsID = 44,
                            Key = (byte)0,
                            Label = "Y",
                            LabelCollectionsID = (short)7
                        },
                        new
                        {
                            LabelsID = 45,
                            Key = (byte)1,
                            Label = "N",
                            LabelCollectionsID = (short)7
                        },
                        new
                        {
                            LabelsID = 46,
                            Key = (byte)0,
                            Label = "Yes",
                            LabelCollectionsID = (short)8
                        },
                        new
                        {
                            LabelsID = 47,
                            Key = (byte)1,
                            Label = "No",
                            LabelCollectionsID = (short)8
                        },
                        new
                        {
                            LabelsID = 48,
                            Key = (byte)0,
                            Label = "F",
                            LabelCollectionsID = (short)9
                        },
                        new
                        {
                            LabelsID = 49,
                            Key = (byte)1,
                            Label = "T",
                            LabelCollectionsID = (short)9
                        },
                        new
                        {
                            LabelsID = 50,
                            Key = (byte)0,
                            Label = "False",
                            LabelCollectionsID = (short)10
                        },
                        new
                        {
                            LabelsID = 51,
                            Key = (byte)1,
                            Label = "True",
                            LabelCollectionsID = (short)10
                        });
                });

            modelBuilder.Entity("StataHelper.Model.Projects", b =>
                {
                    b.Property<short>("ProjectsID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ProjectsID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StataHelper.Model.Variables", b =>
                {
                    b.Property<short>("VariablesID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .HasMaxLength(20);

                    b.Property<short>("ProjectsID");

                    b.Property<string>("Variable")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("VariablesID");

                    b.HasIndex("ProjectsID");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("StataHelper.Model.Varlabs", b =>
                {
                    b.Property<short>("VarlabsID")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("LabelsID");

                    b.Property<int?>("LabelsID1");

                    b.Property<short>("VariablesID");

                    b.HasKey("VarlabsID");

                    b.HasIndex("LabelsID1");

                    b.HasIndex("VariablesID");

                    b.ToTable("Varlabs");
                });

            modelBuilder.Entity("StataHelper.Model.Labels", b =>
                {
                    b.HasOne("StataHelper.Model.LabelCollections", "LabelCollections")
                        .WithMany("Labels")
                        .HasForeignKey("LabelCollectionsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StataHelper.Model.Variables", b =>
                {
                    b.HasOne("StataHelper.Model.Projects", "Projects")
                        .WithMany("Variables")
                        .HasForeignKey("ProjectsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StataHelper.Model.Varlabs", b =>
                {
                    b.HasOne("StataHelper.Model.Labels", "Labels")
                        .WithMany("Varlabs")
                        .HasForeignKey("LabelsID1");

                    b.HasOne("StataHelper.Model.Variables", "Variables")
                        .WithMany("Varlabs")
                        .HasForeignKey("VariablesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
